2022-02-12 19:51:36,262 INFO    MainThread:10987 [internal.py:wandb_internal():91] W&B internal server running at pid: 10987, started at: 2022-02-12 19:51:36.262772
2022-02-12 19:51:36,266 DEBUG   HandlerThread:10987 [handler.py:handle_request():124] handle_request: run_start
2022-02-12 19:51:36,267 INFO    WriterThread:10987 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220212_195135-1b9h0xtr/run-1b9h0xtr.wandb
2022-02-12 19:51:37,823 DEBUG   HandlerThread:10987 [meta.py:__init__():39] meta init
2022-02-12 19:51:37,823 DEBUG   HandlerThread:10987 [meta.py:__init__():53] meta init done
2022-02-12 19:51:37,823 DEBUG   HandlerThread:10987 [meta.py:probe():210] probe
2022-02-12 19:51:37,830 DEBUG   HandlerThread:10987 [meta.py:_setup_git():200] setup git
2022-02-12 19:51:37,857 DEBUG   HandlerThread:10987 [meta.py:_setup_git():207] setup git done
2022-02-12 19:51:37,857 DEBUG   HandlerThread:10987 [meta.py:_save_pip():57] save pip
2022-02-12 19:51:37,858 DEBUG   HandlerThread:10987 [meta.py:_save_pip():71] save pip done
2022-02-12 19:51:37,858 DEBUG   HandlerThread:10987 [meta.py:_save_conda():78] save conda
2022-02-12 19:51:41,051 DEBUG   HandlerThread:10987 [meta.py:_save_conda():86] save conda done
2022-02-12 19:51:41,051 DEBUG   HandlerThread:10987 [meta.py:probe():252] probe done
2022-02-12 19:51:42,476 WARNING MainThread:10987 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-12 19:51:42,692 WARNING MainThread:10987 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-12 19:51:42,692 ERROR   MainThread:10987 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-12 19:51:43,057 INFO    WriterThread:10987 [datastore.py:close():288] close: output/wandb/offline-run-20220212_195135-1b9h0xtr/run-1b9h0xtr.wandb
2022-02-12 19:51:43,059 INFO    HandlerThread:10987 [handler.py:finish():658] shutting down handler
2022-02-12 19:51:43,070 INFO    MainThread:10987 [internal.py:handle_exit():78] Internal process exited
