2022-02-09 22:56:49,241 INFO    MainThread:27535 [internal.py:wandb_internal():91] W&B internal server running at pid: 27535, started at: 2022-02-09 22:56:49.240931
2022-02-09 22:56:49,244 INFO    WriterThread:27535 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220209_225648-27dixn4j/run-27dixn4j.wandb
2022-02-09 22:56:49,247 DEBUG   HandlerThread:27535 [handler.py:handle_request():124] handle_request: run_start
2022-02-09 22:56:50,760 DEBUG   HandlerThread:27535 [meta.py:__init__():39] meta init
2022-02-09 22:56:50,760 DEBUG   HandlerThread:27535 [meta.py:__init__():53] meta init done
2022-02-09 22:56:50,760 DEBUG   HandlerThread:27535 [meta.py:probe():210] probe
2022-02-09 22:56:50,767 DEBUG   HandlerThread:27535 [meta.py:_setup_git():200] setup git
2022-02-09 22:56:50,793 DEBUG   HandlerThread:27535 [meta.py:_setup_git():207] setup git done
2022-02-09 22:56:50,794 DEBUG   HandlerThread:27535 [meta.py:_save_pip():57] save pip
2022-02-09 22:56:50,794 DEBUG   HandlerThread:27535 [meta.py:_save_pip():71] save pip done
2022-02-09 22:56:50,795 DEBUG   HandlerThread:27535 [meta.py:_save_conda():78] save conda
2022-02-09 22:56:53,899 DEBUG   HandlerThread:27535 [meta.py:_save_conda():86] save conda done
2022-02-09 22:56:53,899 DEBUG   HandlerThread:27535 [meta.py:probe():252] probe done
2022-02-09 23:01:42,196 WARNING MainThread:27535 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-09 23:01:42,372 WARNING MainThread:27535 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-09 23:01:42,372 ERROR   MainThread:27535 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-09 23:01:42,983 INFO    WriterThread:27535 [datastore.py:close():288] close: output/wandb/offline-run-20220209_225648-27dixn4j/run-27dixn4j.wandb
2022-02-09 23:01:43,312 INFO    SenderThread:27535 [sender.py:finish():947] shutting down sender
2022-02-09 23:01:43,312 INFO    MainThread:27535 [internal.py:handle_exit():78] Internal process exited
